### ISSUE TITLE
Ao clicar sobre o link "mapa" ao lado do endereço do rodapé, a página não abre

### ISSUE THREAD

**Issue by rdrgmoraes** [I-Value/CMS#100]
![image](https://cloud.githubusercontent.com/assets/17769443/14835629/15d53484-0be1-11e6-8f1f-f047866b7c0a.png)

![image](https://cloud.githubusercontent.com/assets/17769443/14835616/024c853e-0be1-11e6-9328-b143038eeb2f.png)

**Comment by lucianonetto** [comment]
Já tem uma issue sobre esse problema #85
