### ISSUE TITLE
Label

### ISSUE THREAD

**Issue by stefanobaldo** [I-Value/CMS#101]
<img width="251" alt="screen shot 2016-04-27 at 11 08 34" src="https://cloud.githubusercontent.com/assets/1918151/14855024/7399578a-0c68-11e6-937c-a972cd9e5ecf.png">

**Este** escritório é a matriz! 😝

**Comment by jesse1983** [comment]
OK, impedi de tirar a `matriz` da `matriz`

**Comment by stefanobaldo** [comment]
@jesse1983, impedir de "tirar a matriz da matriz" é uma coisa que precisava fazer, mas esse issue não era sobre isso, era uma alteração simples de label. Você fez? Caso positivo, é só fechar de novo.

**Comment by jesse1983** [comment]
Sim
