### ISSUE TITLE
Configurar as opções de modelo

### ISSUE THREAD

**Issue by lucianonetto** [I-Value/CMS#102]
Hoje quando é criado o site e escolhido o modelo, não traz os destaques referente ao modelo e sim um único padrão.

**Comment by jesse1983** [comment]
@lucianonetto Por favor, verifique se está ok.

**Comment by lucianonetto** [comment]
**Modelo 01**
Topo - ok
Super destaque - errado
Lançamentos - errado
Destaque - errado
Chamada - ok
Seguir a imagem http://desenvolvimento:8082/homologacao1/admin/img/cms/templates/THEME01-FULL.jpg

**Modelo 02**
Topo - ok
Super destaque - errado
Lançamentos - errado
Destaque - errado
Chamada - errado
Seguir a imagem http://desenvolvimento:8082/homologacao1/admin/img/cms/templates/THEME02-FULL.jpg

**Modelo 03**
Topo - ok
Super destaque - errado
Lançamentos - ok
Destaque - errado
Chamada - ok
Seguir a imagem http://desenvolvimento:8082/homologacao1/admin/img/cms/templates/THEME03-FULL.jpg

**Modelo 04**
Topo - ok
Super destaque - errado
Lançamentos - errado
Destaque - errado
Chamada - ok
Seguir a imagem http://desenvolvimento:8082/homologacao1/admin/img/cms/templates/THEME04-FULL.jpg

**Modelo 05**
Topo - ok
Super destaque - errado
Lançamentos - ok
Destaque - errado
Chamada - ok
Seguir a imagem http://desenvolvimento:8082/homologacao1/admin/img/cms/templates/THEME05-FULL.jpg

**Modelo 06**
Topo - ok
Super destaque - errado
Lançamentos - errado
Destaque - errado
Chamada - errado
Seguir a imagem http://desenvolvimento:8082/homologacao1/admin/img/cms/templates/THEME06-FULL.jpg

**Modelo 07**
Topo - ok
Super destaque - errado
Lançamentos - ok
Destaque - errado
Chamada - errado
Seguir a imagem http://desenvolvimento:8082/homologacao1/admin/img/cms/templates/THEME07-FULL.jpg

**Modelo 08**
Topo - ok
Super destaque - veio em branco
Lançamentos - veio em branco
Destaque - veio em branco
Chamada - errado
Seguir a imagem http://desenvolvimento:8082/homologacao1/admin/img/cms/templates/THEME08-FULL.jpg

**Comment by jesse1983** [comment]
Teste novamente, por favor @lucianonetto

**Comment by lucianonetto** [comment]
Segue erros encontrados:

Chamada modelo 02 - seguir: http://desenvolvimento:8082/homologacao1/admin/img/cms/templates/THEME02-FULL.jpg

super lançamento modelo 03 - seguir: http://desenvolvimento:8082/homologacao1/admin/img/cms/templates/THEME03-FULL.jpg

Chamada modelo 06 - seguir: http://desenvolvimento:8082/homologacao1/admin/img/cms/templates/THEME06-FULL.jpg

Chamada modelo 07 - seguir: http://desenvolvimento:8082/homologacao1/admin/img/cms/templates/THEME07-FULL.jpg

Chamada modelo 08 - seguir: http://desenvolvimento:8082/homologacao1/admin/img/cms/templates/THEME07-FULL.jpg

**Comment by jesse1983** [comment]
Try again @lucianonetto

**Comment by lucianonetto** [comment]
Modelo 3 ainda está errado o superdestaque.
