### ISSUE TITLE
 Cadastre seu imóvel - Link no topo

### ISSUE THREAD

**Issue by jesse1983** [I-Value/CMS#103]
Está com erro. Vai continuar ali @rdrgmoraes?

**Comment by lucianonetto** [comment]
Creio que não podemos tirar pois está vinculado ao layout, sem esse item ficaria um espaço em branco, comprometendo a estética. http://luciano05.gaiasite.com.br/

**Comment by rdrgmoraes** [comment]
@jesse1983, sim, permanecerá. Eu inclui esta página por padrão na outra issue.

**Comment by lucianonetto** [comment]
**Modelo 01**
Topo - ok
Super destaque - errado
Lançamentos - errado
Destaque - errado
Chamada - ok
Seguir a imagem http://desenvolvimento:8082/homologacao1/admin/img/cms/templates/THEME01-FULL.jpg

**Modelo 02**
Topo - ok
Super destaque - errado
Lançamentos - errado
Destaque - errado
Chamada - errado
Seguir a imagem http://desenvolvimento:8082/homologacao1/admin/img/cms/templates/THEME02-FULL.jpg

**Modelo 03**
Topo - ok
Super destaque - errado
Lançamentos - ok
Destaque - errado
Chamada - ok
Seguir a imagem http://desenvolvimento:8082/homologacao1/admin/img/cms/templates/THEME03-FULL.jpg

**Modelo 04**
Topo - ok
Super destaque - errado
Lançamentos - errado
Destaque - errado
Chamada - ok
Seguir a imagem http://desenvolvimento:8082/homologacao1/admin/img/cms/templates/THEME04-FULL.jpg

**Modelo 05**
Topo - ok
Super destaque - errado
Lançamentos - ok
Destaque - errado
Chamada - ok
Seguir a imagem http://desenvolvimento:8082/homologacao1/admin/img/cms/templates/THEME05-FULL.jpg

**Modelo 06**
Topo - ok
Super destaque - errado
Lançamentos - errado
Destaque - errado
Chamada - errado
Seguir a imagem http://desenvolvimento:8082/homologacao1/admin/img/cms/templates/THEME06-FULL.jpg

**Modelo 07**
Topo - ok
Super destaque - errado
Lançamentos - ok
Destaque - errado
Chamada - errado
Seguir a imagem http://desenvolvimento:8082/homologacao1/admin/img/cms/templates/THEME07-FULL.jpg

**Modelo 08**
Topo - ok
Super destaque - veio em branco
Lançamentos - veio em branco
Destaque - veio em branco
Chamada - errado
Seguir a imagem http://desenvolvimento:8082/homologacao1/admin/img/cms/templates/THEME08-FULL.jpg
