### ISSUE TITLE
Bancos página de financiamento

### ISSUE THREAD

**Issue by lucianonetto** [I-Value/CMS#105]
Inseri novos banco para a página de financiamento, porem não apareceu no site e dependendo da imagem que cadastro não fica certo, fica oval.
![image](https://cloud.githubusercontent.com/assets/6122825/14886909/ae553878-0d29-11e6-8a54-586cfe96cb3a.png)

http://luciano05.gaiasite.com.br/financiamento-e-bancos/

**Comment by stefanobaldo** [comment]
<img width="1015" alt="screen shot 2016-05-09 at 18 05 35" src="https://cloud.githubusercontent.com/assets/1918151/15128170/aa3f75c4-1610-11e6-989a-0e2fe25fe8a3.png">
