### ISSUE TITLE
Simulador do GaiaCrédito

### ISSUE THREAD

**Issue by lucianonetto** [I-Value/CMS#106]
Não consegui habilitar o simulador do gaiacrédito pelo valuegaia, não aparece nem na página de financiamento nem na ficha do imóvel.

**Comment by jesse1983** [comment]
@lucianonetto Não entendi, o problema está no ValueGaia, CMS ou Site?

**Comment by lucianonetto** [comment]
@rdrgmoraes poderia orientar o jessé como será o processo de habilitar o gaiacrédito? não achei esse botão no gaia, teria que ter no CMS?
Achei alguns botões de configuração mas não tem haver com o site do cliente:
![image](https://cloud.githubusercontent.com/assets/6122825/14888569/61334aa0-0d31-11e6-8dd2-8911e9dd2f66.png)

**Comment by jesse1983** [comment]
Minha opinião:
1. @rdrgmoraes Não é possível colocar agora. Até mesmo porque o CMS não estará disponível para todos
2. @rdrgmoraes Não acha que a página `financiamento` não seja substituida por GaiaCrédito quando habilitado?
3. @lucianonetto Consegue listar para o @stefanobaldo os blocos e links que devem aparecer quando o usuário habilita o GaiaCrédito?

**Comment by rdrgmoraes** [comment]
@jesse1983, ao ativar qualquer plano do GaiaCrédito, a página de financiamento deverá adotar o simulador do GaiaCrédito. O usuário poderá escolher entre exibir ou não a página, mas não deverá mais visualizar a opção de página com os simuladores dos bancos.

**Comment by jesse1983** [comment]
@rdrgmoraes Perfeito, é isso mesmo. 
@lucianonetto Por favor, levante tudo que deve mudar aqui nessa tarefa e encaminhe para o Stefano, blz?

**Comment by lucianonetto** [comment]
@stefanobaldo Quando for ver essa tarefa, por favor me chamar para eu te explicar.

**Comment by stefanobaldo** [comment]
@rdrgmoraes Isso precisa ser feito pro MVP? Impede que o produto seja lançado?

**Comment by rdrgmoraes** [comment]
@stefanobaldo, teria que ser feito no MVP porque já possuimos este formato atualmente, se precisar de mais detalhes sobre o fluxo de habilitação posso lhe passar pessoalmente, é só me avisar.
