### ISSUE TITLE
Bug nas vitrines

### ISSUE THREAD

**Issue by jesse1983** [I-Value/CMS#107]
Site: http://jorge_lopes_lima.gaiasite.com.br/
1. Problemas ao coloca 2 vitrines (template 4) juntas
2. Problemas de não aparecer ao escolher template 3 ou 4

**Comment by stefanobaldo** [comment]
Corrigido

**Comment by lucianonetto** [comment]
Template 5 e 6 está conflitando quando tem 2 iguais

**Comment by stefanobaldo** [comment]
Corrigido
