### ISSUE TITLE
Área do cliente

### ISSUE THREAD

**Issue by stefanobaldo** [I-Value/CMS#11]
<img width="247" alt="screen shot 2016-03-10 at 14 40 38" src="https://cloud.githubusercontent.com/assets/1918151/13678556/1ac46a88-e6ce-11e5-8bb1-1341b260a8c8.png">

Estes links devem funcionar? Para que servem? Isto vai entrar no CMS?

**Comment by stefanobaldo** [comment]
Enquanto o Rodrigo não está aqui, o@jesse1983 e @lucianonetto podem responder essa

**Comment by stefanobaldo** [comment]
@rdrgmoraes na área! :smile:

**Comment by rdrgmoraes** [comment]
@stefanobaldo, ainda bem que você tocou neste assunto, precisam entrar no MVP mas não me atendei a ele na lista de itens. Além do CRM (ValueGaia) normalmente os clientes possuem outros softwares para gerir contratos de locação, estes podem ser desenvolvidos por terceiros ou por nós, no caso do GaiaAdm. Será que conseguimos incluir mais este item? Vou conversar com o @jesse1983 sobre este caso.

**Comment by rdrgmoraes** [comment]
@stefanobaldo e @lucianonetto, como o usuário consegue inserir links no menu e no rodapé, por ora vamos remover este item do topo do site, iremos melhorar esta questão fora do MVP.
