### ISSUE TITLE
Posição do botão "Buscar"

### ISSUE THREAD

**Issue by stefanobaldo** [I-Value/CMS#12]
<img width="1171" alt="screen shot 2016-03-10 at 14 44 19" src="https://cloud.githubusercontent.com/assets/1918151/13678670/a9700b5c-e6ce-11e5-8d5b-52ba4025477f.png">

O botão buscar será posicionado de acordo com a quantidade de campos na busca rápida?

**Comment by stefanobaldo** [comment]
@rdrgmoraes e @lucianonetto: se o botão estiver ok podemos fechar este

**Comment by rdrgmoraes** [comment]
@stefanobaldo, sim, seria desta forma. Acho que o @lucianonetto irá aplicar o mesmo conceito do CMS para organizar a área da busca, lá o @jesse1983 fez um esquema interessante...

**Comment by stefanobaldo** [comment]
@jesse1983 você pode ver isso com o @lucianonetto? precisam de mim para algo nessa tarefa?

**Comment by lucianonetto** [comment]
Feito.
