### ISSUE TITLE
Criar solução para topo com logo preenchido para não ficar "buraco branco"

### ISSUE THREAD

**Issue by jesse1983** [I-Value/CMS#121]
Como podemos resolver @rdrgmoraes ?
![screen shot 2016-05-05 at 10 57 00 am](https://cloud.githubusercontent.com/assets/2489514/15045290/2493deaa-12b0-11e6-87d3-4bf6997fd15b.png)

**Comment by rdrgmoraes** [comment]
@jesse1983, permitir a escolha do canvas na tela de upload do logo?

**Comment by jesse1983** [comment]
Estranho. Não seria melhor adequar esse tipo?

**Comment by rdrgmoraes** [comment]
Alterar o modelo?

**Comment by lucianonetto** [comment]
Feito e commitado
