### ISSUE TITLE
Tirar o fundo dos principais bairros

### ISSUE THREAD

**Issue by jesse1983** [I-Value/CMS#126]

**Comment by lucianonetto** [comment]
`<section id="chamadas05" class="bgColor1  hidden-xs">
      <div class="container">
        <div class="row">
          <div class="col-sm-12">
            <div class="chamadaBairros bgColor3">
              <h2>Principais bairros</h2>
              <%
              virtualGaia.Busca objBusca = new virtualGaia.Busca();
              objBusca.pagina = this.Page;    
              objBusca.Gerar();						
              objBusca.quantidade = 12;
              Response.Write(objBusca.geraBairroImoveisLink());
              %>
              <a href="listagem.aspx?cidade2=0" class="btn btn-md bgColor1 bgHover2">Mais bairros</a>
            </div>
          </div>
        </div>
      </div>
    </section>`

**Comment by lucianonetto** [comment]
Retirado a imagem do exemplo http://virtualgaia.com.br/sites/responsive06/

**Comment by rdrgmoraes** [comment]
@lucianonetto, remova o BG e reduza os espaçamentos acima e abaixo dos bairros, isso deve melhorar o aspecto visual, segue abaixo exemplo.

![image](https://cloud.githubusercontent.com/assets/17769443/15087363/9297fe0e-13be-11e6-8357-f35ed4627010.png)

**Comment by lucianonetto** [comment]
Feito.
