### ISSUE TITLE
Banners na home

### ISSUE THREAD

**Issue by jesse1983** [I-Value/CMS#133]
Colocar possibilidade do usuário criar banners na home, subindo imagens e colocando links.

**Comment by jesse1983** [comment]
@stefanobaldo Está pronto, só falta colocar no site. As chaves são:
`home.banners` e `home.banners.body`

**Comment by stefanobaldo** [comment]
Os banners já estão aparecendo no site. Estou jogando o issue pro @lucianonetto agora para dar um "tapa no visu" hehe

**Comment by lucianonetto** [comment]
Feito e commitado
