### ISSUE TITLE
Problemas buscando com encoding utf-8

### ISSUE THREAD

**Issue by jesse1983** [I-Value/CMS#15]
O endpoint de busca de endereços está diferenciando acentos e caracteres especiais. Ex: 

/addresses?q=Benedit,+Cuiab%C3%A1&authorization=devauth

está diferente de:
/addresses?q=Benedit,+Cuiaba&authorization=devauth

**Comment by stefanobaldo** [comment]
@jesse1983 Entendido. Vou focar na parte do site e deixar essas correções na API pra fazer no final. Se for prioridade me avise.
