### ISSUE TITLE
Colocar logo `provisório`

### ISSUE THREAD

**Issue by jesse1983** [I-Value/CMS#16]
Quando o usuário não adicionar um logotipo, colocar um `provisório`. 

Sugestão: usar o http://dummyimage.com/ para gerar o logotipo baseado nas cores e no nome da imobiliária.

**Comment by stefanobaldo** [comment]
@jesse1983 isso é quando for criar um novo site ou migrar um existente pro cms? o usuário consegue remover o logotipo e deixar sem depois que já tem um logo cadastrado?

**Comment by ocipro** [comment]
@jesse1983 Resolvendo essa issue, automaticamente a issue #18 deve ser resolvida.

**Comment by stefanobaldo** [comment]
@ocipro Já que o https://github.com/I-Value/CMS/issues/16, podemos fechar esse também?

**Comment by ocipro** [comment]
Sim @stefanobaldo, ja fechando.
