### ISSUE TITLE
Criar no Backoffice os campos `Usa CMS` e `Versão do CMS` 

### ISSUE THREAD

**Issue by jesse1983** [I-Value/CMS#17]

**Comment by stefanobaldo** [comment]
Foi passado pra Carol fazer - https://i-value.atlassian.net/browse/CMS-111

**Comment by stefanobaldo** [comment]
@jesse1983 e @rdrgmoraes vocês precisam definir a questão da combo "Premium/Free/etc" que deverá aparecer no BackOffice. Isso vai entrar agora no MVP pro dia 29/3?

**Comment by stefanobaldo** [comment]
Já está feito, falta subir em produção
