### ISSUE TITLE
Evento Page.Load() está disparando duas vezes na listagem

### ISSUE THREAD

**Issue by ocipro** [I-Value/CMS#18]
Na listagem.aspx, tem um componente chamado Listing.ascx que coordena as chamadas que carregam a listagem. O evento pageload desse controle está disparando duas vezes, sobrecarregando o servidor. 

Investigar causas e correção.

**Comment by stefanobaldo** [comment]
Boa! :+1:

**Comment by ocipro** [comment]
Descobri a causa do bug. 

O logotipo está ausente para o cliente que estava sendo usado para testes. 
Isso ocasiona, no HTML renderizado,  um img sem src. Quando isso acontece, o Chrome tenta recarregar a pagina (silenciosamente). 

Fazendo com que o pageload ocorra duas vezes.

Um valor default pra essa "propriedade" já sanaria o problema.

**Comment by ocipro** [comment]
#16

**Comment by ocipro** [comment]
Corrigido, fiz uma solução mockando um logo falso. 

Se o logo não for informado no MiniCMS, eu mocko um endereço que gera um logo falso.
Like this:
http://dummyimage.com/rec/000/fff.png&text=I-Value+(no+logo)
