### ISSUE TITLE
Quando criar o site pelo wizard, criar páginas padrão

### ISSUE THREAD

**Issue by jesse1983** [I-Value/CMS#19]
Ter um endpoint ou uma forma de, quando um usuário criar um novo website pelo wizard, criar páginas padrão.

**Comment by stefanobaldo** [comment]
Passar a chave `wizard` quando fizer `PUT /websites/<id>` para criar as páginas _default_

**Comment by stefanobaldo** [comment]
@jesse1983 testar e fechar a tarefa
