### ISSUE TITLE
Criar plano no BackOffice

### ISSUE THREAD

**Issue by stefanobaldo** [I-Value/CMS#22]
Deverá ser criado uma opção para selecionar o plano do CMS do cliente no BackOffice

**Comment by stefanobaldo** [comment]
@jesse1983 @rdrgmoraes Free? Premium? O que mais?
O consultor poderá alterar isso diretamente via BackOffice?
Isso orecisa entrar pro MVP do dia 29/3? (início da utilização interna).

**Comment by rdrgmoraes** [comment]
@stefanobaldo, a tarefa foi inserida na sprint 10: https://i-value.atlassian.net/browse/CMS-96

**Comment by stefanobaldo** [comment]
@rdrgmoraes valeu, mas lá a tarefa não está descrita pelo que vi, e eu não sei nem bem em qual sprint estamos mais, estamos nos desdobrando pra fazer um esforço final aqui pra entregar o MVP, então vamos discutir aqui para facilitar - se puder responder essas perguntas que coloquei aí em cima já agiliza pra eu coordenar aqui

**Comment by stefanobaldo** [comment]
@rdrgmoraes entendi que deverá entrar já agora pro dia 29/3, então só queria saber o seguinte:

- As opções são somente `Free` e `Premium`?
- O consultar vai alterar isso livremente via BackOffice?
- Ao criar o site, ele entra em qual plano?

**Comment by rdrgmoraes** [comment]
Inicialmente sim, mas possivelmente haverão outros planos no futuro, devemos deixar tudo preparado para este cenário. O consultor poderá alterar este item livremente via backoffice, mas ao alterar de "Premium" para "Free" ou para um status provisório (sugiro o status cancelamento), teremos um fluxo de deverá ocorrer no front do Gaia, o usuário deverá confirmar o cancelamento do serviço para guardarmos um log de "quem" realizou a confirmação do cancelamento do plano, neste momento o usuário deverá ser alertado que todas as alterações realizadas serão descartadas em definitivo, ao aceitar o usuário deverá ser conduzido novamente para o Wizard onde irá reconfigurar seu site na versão free, e apenas ao concluí-lo devemos alterar seu plano.

**Comment by stefanobaldo** [comment]
@jesse1983 o que me diz?

**Comment by stefanobaldo** [comment]
@rdrgmoraes para o MVP 29/3 podemos somente colocar a opção free/premium no backoffice e restringir as opções do menu?

**Comment by jesse1983** [comment]
@stefanobaldo Minha opinião:

***Backoffice***:  criar os campos: `Usa CMS` e `Plano do CMS` como um select. Importante apenas mostrar como readonly o campo `Versão do CMS`

***GaiaCore API*** - Criar os dois campos

***Gaia/CMS***  - Vou alinhar com o Rodrigo quais itens estarão disponíveis para o Free. Já estamos trabalhando na parte de layout e já está alinhado para faremos.

**Comment by stefanobaldo** [comment]
:+1:

**Comment by stefanobaldo** [comment]
@jesse1983 valide isto:

<img width="404" alt="screen shot 2016-03-16 at 11 27 26" src="https://cloud.githubusercontent.com/assets/1918151/13815629/1f4e5a6e-eb6a-11e5-8796-1f729dd93f18.png">

**Comment by jesse1983** [comment]
Show!

**Comment by stefanobaldo** [comment]
Ok, são 3 frentes nessa tarefa:

- API - _concluído_
- Backoffice
- Front

Vou deixar essa _issue_ aberta até que a parte do Backoffice e Front sejam concluídas.

**Comment by stefanobaldo** [comment]
API - _concluído_
Backoffice - _concluído_

Serão abertas novas tarefas para a parte de front e deploy do Backoffice.
