### ISSUE TITLE
Recaptcha

### ISSUE THREAD

**Issue by stefanobaldo** [I-Value/CMS#23]
Criar chave de recaptcha via API

**Comment by stefanobaldo** [comment]
@rdrgmoraes @jesse1983 @ocipro vamos discutir um pouco essa tarefa

**Comment by stefanobaldo** [comment]
Eu sinceramente penso que neste momento não seja interessante que a gente perca tempo tentando automatizar esse processo. O @ocipro já reportou algumas dificuldades técnicas pra implementar esta solução em pouco tempo e talvez para o MVP seria interessante pensarmos em alternativas.

**Comment by jesse1983** [comment]
Concordo @stefanobaldo. Não é essencial pro MVP.

**Comment by ocipro** [comment]
Mais sobre o tema:

http://stackoverflow.com/questions/17800552/multi-domain-multi-client-recaptcha-use
http://stackoverflow.com/questions/32881789/recaptcha-allow-for-all-domains-or-add-via-api
http://stackoverflow.com/questions/32191250/how-can-i-use-recaptcha-v2-on-a-large-number-of-domains
http://stackoverflow.com/questions/24755134/no-more-recaptcha-global-key-option?lq=1
https://forum.myroundcube.com/topic/19-google-removed-global-keys-from-their-free-recaptcha-service/

**Comment by rdrgmoraes** [comment]
Sugiro possibilitarmos ao usuário o uso do captcha antigo e a configuração manual do recaptcha. Conversei com o @ccesara sobre o sistema de validação e infelizmente o mesmo não estará disponível para o MVP. Não permitimos a configuração de nenhum sistema de validação irá ocasionar spam nos formulários e injeção de código de maliciosos sem que exista nenhum sistema para barrar este tipo de ação em nossa ponta.

**Comment by rdrgmoraes** [comment]
Apenas complementando, não descarto o uso de alternativas...

http://pt.stackoverflow.com/questions/17456/como-prevenir-spam-em-formul%C3%A1rios-de-contato-sem-usar-captcha

**Comment by stefanobaldo** [comment]
@rdrgmoraes eu descarto, acho que qualquer validação _client-side_ não oferece segurança e pode ser burlada facilmente; é claro que alguma coisa é melhor que nada, mas não vejo motivo para fazer um esforço para implementar uma solução alternativa _client-side_ que não será utilizada no futuro - não é melhor trabalharmos disso após a entrega do MVP, quando vocês estiverem testando o sistema internamente por exemplo?

**Comment by stefanobaldo** [comment]
@jesse1983 @ocipro pitacos are welcome

**Comment by rdrgmoraes** [comment]
@stefanobaldo, não podemos esquecer que assim que finalizarmos o MVP o CMS será aplicado na prática e com clientes reais. Deixar o site destes clientes sem captcha ou recaptcha é fato que teremos reclamações. Atualmente publicamos uma média de 80 sites a cada 15 dias, note o volume e a proporção que isso irá ganhar em pouco tempo...

**Comment by stefanobaldo** [comment]
@rdrgmoraes e qual a possibilidade de criarmos as chaves pro cliente nesse primeiro momento enquanto trabalhamos em uma solução? entenda, minha única preocupação é liberar isso dia 29 sem atrasos

**Comment by rdrgmoraes** [comment]
@jesse1983 podemos preparar o CMS para receber os dados necessários ao funcionamento do recaptcha do Google? As opções seriam, sem recaptcha ou com recaptcha e teriamos os campos para inserção das chaves geradas através do site oficial.

**Comment by stefanobaldo** [comment]
@rdrgmoraes isso é tranquilo pra fazermos aqui - acho uma boa solução
@jesse1983? @ocipro?

**Comment by ocipro** [comment]
@rdrgmoraes, pra mim é a melhor solução, pede pra alguém fazer uma arte, pra guiar o usuário leigo no processo. 
As chaves viram parâmetros vindos do CMS.

Mundo perfeito.


Artigo explicando como o usuário obtém uma chave:
http://www.aspsnippets.com/Articles/Get-Google-RECaptcha-Site-Key-Public-Key-and-Secret-Key-Private-Key.aspx

**Comment by stefanobaldo** [comment]
@rdrgmoraes fechou?

**Comment by rdrgmoraes** [comment]
@stefanobaldo, se o @jesse1983 estiver de acordo fechou, vamos preparar um artigo no GaiaWiki ensinando o cliente a realizar os procedimentos e gerar as chaves.

**Comment by stefanobaldo** [comment]
<img width="401" alt="screen shot 2016-03-16 at 16 48 56" src="https://cloud.githubusercontent.com/assets/1918151/13826594/fe0d5742-eb96-11e5-960a-3cebd37c4049.png">

**Comment by rdrgmoraes** [comment]
http://codepen.io/BoringCode/pen/FfzLs

@ocipro, o AliExpress usa uma solução parecida com essa para evitar spam bots, o que você acha?

**Comment by ocipro** [comment]
![image](https://cloud.githubusercontent.com/assets/10051346/14219503/ee144d7c-f830-11e5-93f3-c535bbf924ce.png)


Done.


Utilizado chaves gravadas no CMS.
