### ISSUE TITLE
Bug no filtro da vitrine

### ISSUE THREAD

**Issue by stefanobaldo** [I-Value/CMS#25]
Na descrição do filtro está indicando somente imóveis marcados como `Destaque`, mas quando você clica em editar o dropdown indica `Todos`

**Comment by stefanobaldo** [comment]
<img width="1109" alt="screen shot 2016-03-21 at 11 06 51" src="https://cloud.githubusercontent.com/assets/1918151/13921093/0bd19df4-ef55-11e5-9836-6b3ce8109e3f.png">
<img width="432" alt="screen shot 2016-03-21 at 11 05 05" src="https://cloud.githubusercontent.com/assets/1918151/13921098/10a99f16-ef55-11e5-9889-1e3616280884.png">

**Comment by stefanobaldo** [comment]
Está acontecendo para vitrines com abas - verificar nas vitrines sem abas também

**Comment by jesse1983** [comment]
Consegue replicar esse bug também, @stefanobaldo?
