### ISSUE TITLE
Bug no título da vitrine

### ISSUE THREAD

**Issue by stefanobaldo** [I-Value/CMS#26]
Mesmo configurando o título da vitrine, ao criar ele não mostra o título na tela

**Comment by stefanobaldo** [comment]
<img width="1155" alt="screen shot 2016-03-21 at 11 26 51" src="https://cloud.githubusercontent.com/assets/1918151/13921696/eda160c8-ef57-11e5-9d0a-52ebca21880c.png">
<img width="901" alt="screen shot 2016-03-21 at 11 26 45" src="https://cloud.githubusercontent.com/assets/1918151/13921703/f3d82da0-ef57-11e5-994b-8838802b62ac.png">

**Comment by stefanobaldo** [comment]
Acontece nos layouts com abas - testar para os outros

**Comment by jesse1983** [comment]
Consegue replicar o bug novamente @stefanobaldo?
