### ISSUE TITLE
Criar mais imagens dos topos

### ISSUE THREAD

**Issue by jesse1983** [I-Value/CMS#32]
Imagens como a http://desenvolvimento:8082/homologacao1/admin/img/cms/templates/THEME03.jpg devem ter:

- [ ] Criar uma imagem inteira do website na mesma largura (THEME03-FULL.jpg)
- [ ] Criar mesma imagem, mas com hightlight só para o topo (THEME03-TOP-HIGHLIGHT.jpg)

**Comment by lucianonetto** [comment]
Imagens feitas!
