### ISSUE TITLE
No menu do site, está aparecendo o texto "Back" ao invés de "Voltar

### ISSUE THREAD

**Issue by jesse1983** [I-Value/CMS#35]

**Comment by ocipro** [comment]
![image](https://cloud.githubusercontent.com/assets/10051346/14178572/9766c108-f731-11e5-92b6-d1d884560d16.png)

Done.

**Comment by ocipro** [comment]
ps.: Como foi alteração de js, é preciso rodar novamente o gulp. (depois de um git pull)
