### ISSUE TITLE
Criar último template de vitrine com abas

### ISSUE THREAD

**Issue by stefanobaldo** [I-Value/CMS#5]
Faltou um template da vitrine de imóveis (o último de imóveis) que deveria ter abas

**Comment by lucianonetto** [comment]
<section class="destaque03 bgColor3 hidden-xs">
    <div class="container">
      <div class="row">
        <div class="topoNav col-xs-12">
          <h2>Mais destaques</h2>
          <ul class="jsNavAbas">
            <li><a data-box="desCasa" class="borderColor1 color2 cHover1" href="javascript:;" data-page="modelo/_destaques_casas-03.aspx">Casas</a></li>
            <li><a data-box="desApartamento" class="borderColor1 color2 cHover1" href="javascript:;" data-page="modelo/_destaques_apartamentos-03.aspx">Apartamentos</a></li>
            <li><a data-box="desTerreno" class="borderColor1 color2 cHover1" href="javascript:;" data-page="modelo/_destaques_terrenos-03.aspx">Terrenos</a></li>
          </ul>
        </div>
        <div class="boxAllDesc jsConteudoNav">
          <div class="categoriasImoveisDestaque jsHidden" id="desCasa"> </div>
          <div class="categoriasImoveisDestaque jsHidden" id="desApartamento"> </div>
          <div class="categoriasImoveisDestaque jsHidden" id="desTerreno"> </div>
        </div>
      </div>
    </div>
  </section>


<%
			Destaques objDestCasas = new Destaques();
			objDestCasas.pagina = this.Page;
			objDestCasas.eOrdem = ordem.aleatorio;
			objDestCasas.eTipo = new tipo[] { tipo.casa };
			objDestCasas.maxDescricao = 120;
			objDestCasas.quantidade = 8;
			objDestCasas.destaque = true;
			objDestCasas.tiraCentavos = true;
			objDestCasas.template = "<div class='col-xs-12 col-sm-6 col-md-3'>" + Environment.NewLine;
			objDestCasas.template += "<div class='destaque borderHover1'>" + Environment.NewLine;
			objDestCasas.template += "	<div class='image'>[foto-url-amigavel]</div>" + Environment.NewLine;
			objDestCasas.template += "	<div class='features'>" + Environment.NewLine;
			objDestCasas.template += "	<p>[tx_tipo] - [tx_bairro]</p>" + Environment.NewLine;
			objDestCasas.template += "	</div>" + Environment.NewLine;
			objDestCasas.template += "</div>" + Environment.NewLine;
			objDestCasas.template += "</div>" + Environment.NewLine;
			objDestCasas.Gerar();
%>
<div class="col-xs-12"><a href="listagem.aspx?tipo=7" class="btn btn-md bgColor1 bgHover2 visible-xs desCasa">Mais casas</a></div>

**Comment by lucianonetto** [comment]
```
<%
			Destaques objDestCasas = new Destaques();
			objDestCasas.pagina = this.Page;
			objDestCasas.eOrdem = ordem.aleatorio;
			objDestCasas.eTipo = new tipo[] { tipo.casa };
			objDestCasas.maxDescricao = 120;
			objDestCasas.quantidade = 8;
			objDestCasas.destaque = true;
			objDestCasas.tiraCentavos = true;
			objDestCasas.template = "<div class='col-xs-12 col-sm-6 col-md-3'>" + Environment.NewLine;
			objDestCasas.template += "<div class='destaque borderHover1'>" + Environment.NewLine;
			objDestCasas.template += "	<div class='image'>[foto-url-amigavel]</div>" + Environment.NewLine;
			objDestCasas.template += "	<div class='features'>" + Environment.NewLine;
			objDestCasas.template += "	<p>[tx_tipo] - [tx_bairro]</p>" + Environment.NewLine;
			objDestCasas.template += "	</div>" + Environment.NewLine;
			objDestCasas.template += "</div>" + Environment.NewLine;
			objDestCasas.template += "</div>" + Environment.NewLine;
			objDestCasas.Gerar();
%>
<div class="col-xs-12"><a href="listagem.aspx?tipo=7" class="btn btn-md bgColor1 bgHover2 visible-xs desCasa">Mais casas</a></div>
```

**Comment by stefanobaldo** [comment]
<img width="1166" alt="screen shot 2016-03-14 at 11 49 18" src="https://cloud.githubusercontent.com/assets/1918151/13748257/ca30d718-e9da-11e5-8127-1d4e43b62077.png">

**Comment by stefanobaldo** [comment]
@lucianonetto é isso aí? podemos fechar a tarefa?

**Comment by lucianonetto** [comment]
Faltou o botão mais imóveis ao lado das abas, conforme http://desenvolvimento/sites/novopremium.com.br/2015/index-08.aspx

**Comment by stefanobaldo** [comment]
@lucianonetto neste modelo a section tem o id `destaque03` - para 01 e 02 o botão aparece, provavelmente precisa ajeitar o css
