### ISSUE TITLE
Aumentar o espaçamento do logotipo do topo

### ISSUE THREAD

**Issue by jesse1983** [I-Value/CMS#56]
Se o usuário subir o logotipo "cheio", fica grudado com o topo. Ex:

![screen shot 2016-03-31 at 17 44 57](https://cloud.githubusercontent.com/assets/2489514/14189980/aa9a5ca0-f766-11e5-8305-3cd12acf001d.png)

**Comment by lucianonetto** [comment]
@jesse1983 essa foi uma solicitação do @rdrgmoraes para aqueles clientes que sobem imagem com cor no fundo, Rodrigo, veja como devemos deixar o espaço para o logo, com ou sem espaço.

**Comment by jesse1983** [comment]
@rdrgmoraes há duas formas de resolver isso:

1. Orientar o usuário cortar o logotipo
2. Criar uma configuração para ele escolher os paddings

**Comment by rdrgmoraes** [comment]
@jesse1983, acredito que o próprio crop/resize pode resolver esta questão, permitir o usuário reduzir a imagem além da área delimitada e escolher a cor do canvas.

**Comment by jesse1983** [comment]
**Prós**: 

1. Já está pronto

**Contras**:

1. Muitos usuários não entenderão que terão que _cortar_ o logotipo pra ajustá-lo.
2. O logotipo ficará menor também no rodapé

**Comment by rdrgmoraes** [comment]
Se já está pronto, vamos testar com usuários reais e se necessário alteramos no futuro.

**Comment by lucianonetto** [comment]
Inserido 10px de top e 10px de bottom.
