### ISSUE TITLE
Destaque com abas

### ISSUE THREAD

**Issue by lucianonetto** [I-Value/CMS#58]
O último destaque com abas quando é carregado aparecem 2 botões "ver mais"

![image](https://cloud.githubusercontent.com/assets/6122825/14217798/8e823914-f826-11e5-9143-2728add2e706.png)

**Comment by ocipro** [comment]
![image](https://cloud.githubusercontent.com/assets/10051346/14359388/92549bae-fcc7-11e5-9a45-7fae3428a503.png)


Corrigido já. 

Apareceu problema quando criado título contendo "aspas". Já tratado.
