### ISSUE TITLE
Sumir categoria de menu quando não tem item

### ISSUE THREAD

**Issue by lucianonetto** [I-Value/CMS#59]
Precisa sumir com a categoria de menu quando não possui itens.
ex: institucional
![image](https://cloud.githubusercontent.com/assets/6122825/14217949/832f3ef8-f827-11e5-8ae0-03116bc63bc4.png)

**Comment by ocipro** [comment]
![image](https://cloud.githubusercontent.com/assets/10051346/14260208/c8c38072-fa80-11e5-84cf-b467dbc20f18.png)


Done!
