### ISSUE TITLE
Verificar URL rewrites

### ISSUE THREAD

**Issue by stefanobaldo** [I-Value/CMS#6]
Verificar todos os rewrites do web.config

**Comment by stefanobaldo** [comment]
- O site deve funcionar sem precisar passar a página inicial index.aspx
- As páginas deverão carregar quando ocultada a extensão .aspx
- Os slugs definidos pelo usuário no CMS deverão redirecionar para as páginas correspondentes
- A URL /imovel/xxxxxxx/referencia deverá funcionar e aceitar referência com ou sem o sufixo da imobiliária (-XXX)

**Comment by ocipro** [comment]
blacklist para slugs, não usar nenhum dos slugs abaixo:

/listagem 
/imoveis
/imovel-detalhes
/imovel
/listagemEmpreendimento
/empreendimentos
/empreendimento-detalhes
/lancamento
/listagemCondominio
/condominios
/condominio-detalhes
/condominio
