### ISSUE TITLE
Script e Css

### ISSUE THREAD

**Issue by lucianonetto** [I-Value/CMS#64]
Inseri um script e um css porem não replicou no site.
![image](https://cloud.githubusercontent.com/assets/6122825/14316967/4dbfe444-fbdc-11e5-9551-88b45835e3c1.png)

**Comment by ocipro** [comment]
![image](https://cloud.githubusercontent.com/assets/10051346/14366276/491f98e6-fce8-11e5-98f9-323ed13f9cec.png)


Done!
