### ISSUE TITLE
Configuração analytics

### ISSUE THREAD

**Issue by lucianonetto** [I-Value/CMS#65]
Coloquei um código UA porem não replicou no site, e também está aparecendo o dóminio da i-value e não o do cliente.
![printcms](https://cloud.githubusercontent.com/assets/6122825/14317117/123e60fc-fbdd-11e5-87dc-0a758be67d70.jpg)

**Comment by ocipro** [comment]
![image](https://cloud.githubusercontent.com/assets/10051346/14386115/d9d78010-fd79-11e5-9073-cbf203908bd1.png)


Done!
