### ISSUE TITLE
Exibir foto empreendimento na ficha do imóvel

### ISSUE THREAD

**Issue by lucianonetto** [I-Value/CMS#67]
Marquei para não exibir as fotos do empreendimento na ficha do imóvel, porem continuam aparecendo.
Ex: http://cms.valuegaia.com.br/imovel/casa-residencial-venda-jardim-jurema-valinhos-sp/ca2642/

**Comment by ocipro** [comment]
![image](https://cloud.githubusercontent.com/assets/10051346/14385163/5ed66024-fd75-11e5-8b01-0d42cf71d005.png)


Done!
