### ISSUE TITLE
Configurações de mapa na ficha de impressão

### ISSUE THREAD

**Issue by lucianonetto** [I-Value/CMS#70]
As configurações de mapa não estão alterando o mapa da ficha de impressão.

**Comment by ocipro** [comment]
![image](https://cloud.githubusercontent.com/assets/10051346/14362848/ca0b0776-fcd7-11e5-81d2-37c71c55b223.png)


![image](https://cloud.githubusercontent.com/assets/10051346/14362861/d836ad82-fcd7-11e5-95e7-c93da587d7a5.png)

![image](https://cloud.githubusercontent.com/assets/10051346/14362867/e3ebfeac-fcd7-11e5-99df-6173720d1407.png)


Done!
