### ISSUE TITLE
Cadastro de páginas modelo

### ISSUE THREAD

**Issue by lucianonetto** [I-Value/CMS#73]
Retirar a página "cadastros"
Precisa inserir as páginas:
 - Cadastro Locatário
 - Cadastro Proposta

**Comment by ocipro** [comment]
![image](https://cloud.githubusercontent.com/assets/10051346/14328403/e16b2f48-fc0c-11e5-9ecd-1fdad1cd7a91.png)

Precisa alterara o tx_ref da página default Cadastros, atualmente aponta para /cadastros/index.aspx
Alterar para /cadastros.aspx


![image](https://cloud.githubusercontent.com/assets/10051346/14328432/0bb4cea8-fc0d-11e5-986f-a7c9e2833902.png)


Adicionar também na mesma tabela, referencia para as páginas

/cadastro-locatario.aspx
/cadastro-proposta.aspx

/cadastro-imovel.aspx já está cadastrado.

**Comment by jesse1983** [comment]
Concluído

**Comment by jesse1983** [comment]
Done!
