### ISSUE TITLE
Login Universidade Corporativa

### ISSUE THREAD

**Issue by lucianonetto** [I-Value/CMS#78]
Verificar como será feito a parte de login da universidade corporativa, hoje está sendo criada através de script, não está dinâmico.

**Comment by jesse1983** [comment]
@rdrgmoraes Quem deve criar esse login, o cliente ou nossa equipe?

**Comment by rdrgmoraes** [comment]
@lucianonetto, vou precisar de mais detalhes sobre como front-end atua nesta atividade para entender como podemos automatizar este processo.

**Comment by lucianonetto** [comment]
@rdrgmoraes Hoje o login é criado pela equipe do Benjamin e enviado por chamado através do jira, pegamos o link e inserimos direto no js do site, onde replica nos botões.
Creio que o ideal seria tem um campo no cms para inserir a url do login, como campo obrigatório quando é ativada a página da universidade corporativa.

**Comment by rdrgmoraes** [comment]
@jesse1983, precisaremos de um campo no backoffice por enquanto, a equipe do GaiaEdu irá inserir lá esta URL mencionada pelo Luciano. O usuário não possui acesso em nenhum momento a estas informações, por isso não temos como incluir isso na ponta do CMS.

**Comment by jesse1983** [comment]
@rdrgmoraes Ficará assim então:
Usuário do Backoffice habilita a universidade corporativa e coloca o link. Automaticamente é criado uma página no website com o link correto e o usuário da imobiliária pode desabilitar essa página via CMS se necessário.

Logo, precisamos
- [ ] Criar os campos `Ativar Universidade Gaia` e `Link da Universidade Gaia` dentro do **Backoffice** @stefanobaldo 
- [ ] Criar o atributo no GaiaCore indicando se ativou a Universidade Gaia @stefanobaldo 
- [ ] Colocar o link da Universidade Gaia na página dentro do website @lucianonetto 
- [ ] Criar no CMS como a página padrão que só poderá ser habilitada se a imobiliária ativou Universidade Gaia @jesse1983

**Comment by lucianonetto** [comment]
@rdrgmoraes Conversei com o Armando, e parece que o login da universidade gaia será único, não será mais um para cada cliente, com isso creio que podemos eliminar a criação desse campo do backoffice, por favor alinhe com ele como será o novo processo.

**Comment by rdrgmoraes** [comment]
Ok, vou alinhar com o Armando e retorno com uma decisão sobre este ponto.

**Comment by rdrgmoraes** [comment]
@lucianonetto: http://signin.i-value.com.br/?provider=gaiaedu

**Comment by lucianonetto** [comment]
Inserido o link de login nos botões, @stefanobaldo conforme conversado, por favor deixar esse link dinâmico trazendo direto do banco.

**Comment by stefanobaldo** [comment]
Estou fechando essa issue e deixando o link direto no código como está, porém como hoje temos um website único, se precisar mudar o link é só alterar na página padrão que é automaticamente alterado para todos. Futuramente caso haja demanda de alteração frequente nós criamos um campo no banco e modificamos o código.
