### ISSUE TITLE
Não está ordenando o menu corretamente no site

### ISSUE THREAD

**Issue by jesse1983** [I-Value/CMS#79]
Dados:
![screen shot 2016-04-14 at 15 02 53](https://cloud.githubusercontent.com/assets/2489514/14538040/29cb96bc-0250-11e6-9642-a2367eee3260.png)

CMS:
![image](https://cloud.githubusercontent.com/assets/2489514/14538057/3b09efe6-0250-11e6-8aee-93905454011b.png)

Site:
![image](https://cloud.githubusercontent.com/assets/2489514/14538073/48d12194-0250-11e6-8934-77e6255cb5b6.png)
![image](https://cloud.githubusercontent.com/assets/2489514/14538084/53f560bc-0250-11e6-9462-32b69352c948.png)

**Comment by stefanobaldo** [comment]
Corrigido

**Comment by lucianonetto** [comment]
Testei  e está ok.
