### ISSUE TITLE
Erro ao incluir página padrão

### ISSUE THREAD

**Issue by jesse1983** [I-Value/CMS#81]
Verificar na API o que ocorreu:
```shell
curl 'http://54.232.96.79:3000/websites/336/pages' -H 'Origin: http://desenvolvimento:8082' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: pt-BR,pt;q=0.8,en-US;q=0.6,en;q=0.4' -H 'Authorization: 0c5d0a323fb26df9a29229560dacadee' -H 'Content-Type: application/json' -H 'Accept: ​*/*​' -H 'Referer: http://desenvolvimento:8082/homologacao1/admin/default.aspx' -H 'User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36' -H 'Proxy-Connection: keep-alive' --data-binary '{"type":"DEFAULT","category":"/websites/336/page_categories/26","title":"Cadastro de proposta","slug":"cadastro-de-proposta","default_page":"/default_pages/20","locked":false,"menu_visibility":true}' --compressed
```

**Comment by jesse1983** [comment]
Mais um exemplo:
`curl 'http://54.232.96.79:3000/websites/336/pages' -H 'Origin: http://desenvolvimento:8082' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: en-US,en;q=0.8,pt;q=0.6' -H 'Authorization: 494b832c94f278bae917e4b0daaed2d2' -H 'Content-Type: application/json' -H 'Accept: */*' -H 'Referer: http://desenvolvimento:8082/homologacao1/admin/default.aspx' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36' -H 'Connection: keep-alive' --data-binary '{"type":"DEFAULT","category":"/websites/336/page_categories/53","title":"Avalie seu corretor","slug":"avalie-seu-corretor","default_page":"/default_pages/16","locked":false,"menu_visibility":true}' --compressed`

**Comment by stefanobaldo** [comment]
Corrigido

**Comment by lucianonetto** [comment]
Algumas vezes quando vou adiciona uma nova página modelo, a página fica em branco e não aparece os modelos:

![image](https://cloud.githubusercontent.com/assets/6122825/14965967/a3d519f8-1086-11e6-8954-0b3ff4364e9c.png)

E quando aparece fica quebrado:
![image](https://cloud.githubusercontent.com/assets/6122825/14965992/c2963ad4-1086-11e6-92d6-65326d24b826.png)

**Comment by stefanobaldo** [comment]
Não consegui reproduzir a página ficando em branco, mas o layout está realmente quebrado. @jesse1983, estou repassando pra você dar uma olhada.

**Comment by jesse1983** [comment]
Corrigido
