### ISSUE TITLE
Configurar o link da Universidade Gaia

### ISSUE THREAD

**Issue by jesse1983** [I-Value/CMS#83]
A chave é `CONFIG.LINK_UNIVERSIDADE`

**Comment by jesse1983** [comment]
@rdrgmoraes Como vamos ficar com o link da Universidade Gaia? Estará disponível no CMS para qualquer cliente configurar (acredito que não)? Ou deveria aparecer apenas se a imobiliária comprou a Universidade Corporativa? Nos explique como você quer o processo, ok?

**Comment by rdrgmoraes** [comment]
@jesse1983, o ideal é que a Universidade Corporativa esteja sempre disponível no CMS, para qualquer cliente. Para aqueles que já contrataram, possibilitar a inclusão (sim ou não) no site, para aqueles que não contrataram, ao tentar incluir devemos exibir um formulário para captação deste lead para a equipe de vendas do GaiaEdu.

**Comment by jesse1983** [comment]
@rdrgmoraes OK, só vou precisar do link da landing page que deverei enviar quando o usuário não comprou ainda a Universidade.

@stefanobaldo Vou precisar que, no GaiaCore, tenha uma informação na `agency` se contratou a Universidade Gaia.

**Comment by rdrgmoraes** [comment]
@jesse1983, a ideia é que seja aberta uma pop-up contendo um formulário, podemos fazer algo simples e provisório enquanto providencio algo junto a equipe de comunicação. Assim  que estiver atuando nesta atividade me chame e te passo mais detalhes sobre os campos e o e-mail de destino do formulário.

**Comment by stefanobaldo** [comment]
@rdrgmoraes Isso precisa ser feito pro MVP? Impede que o produto seja lançado?

**Comment by rdrgmoraes** [comment]
@stefanobaldo, sim, para o MVP pois deste o Gaiathon esta atividade estava prometida para o Benjamin.

**Comment by stefanobaldo** [comment]
Backoffice OK
Site OK
API OK
Repassando issue para o @jesse1983 para alterar o front
