### ISSUE TITLE
Está aparecendo 2 telefones iguais

### ISSUE THREAD

**Issue by jesse1983** [I-Value/CMS#84]
http://jesse_pinheiro.gaiasite.com.br/
jessebpinheiro@gmail.com
123456

![screen shot 2016-04-19 at 11 44 00](https://cloud.githubusercontent.com/assets/2489514/14642754/16575398-0622-11e6-969d-fef3907ecf6c.png)

**Comment by stefanobaldo** [comment]
<img width="305" alt="screen shot 2016-04-27 at 10 52 08" src="https://cloud.githubusercontent.com/assets/1918151/14854436/1a829da2-0c66-11e6-93c7-30e3b4b44a15.png">

Corrigido

**Comment by lucianonetto** [comment]
testei e está ok.
