### ISSUE TITLE
Definir links padrões do menu do site

### ISSUE THREAD

**Issue by lucianonetto** [I-Value/CMS#89]
Creio que quando é criado o site, não deve vir a página institucional, boletos, universidade corporativa e etc.

**Comment by jesse1983** [comment]
@rdrgmoraes Concorda?

**Comment by rdrgmoraes** [comment]
@jesse1983, concordo, o site ao ser criado deve vir o mais enxuto possível, o usuário configura o resto.

**Comment by jesse1983** [comment]
@rdrgmoraes Pode fazer uma lista de todos que você quer que tenha?

**Comment by rdrgmoraes** [comment]
Por  padrão acredito que deveríamos manter apenas a homepage, as listagens, as fichas e a página de contato. O usuário deverá adicionar qualquer outra página via CMS.

**Comment by jesse1983** [comment]
@rdrgmoraes Abaixo está o padrão. Check o que você quer manter:

- [ ] Institucional -	Imobiliária
- [ ] Institucional -	Avalie seu corretor
- [ ] Imóveis -	Encomende seu imóvel
- [ ] Imóveis -	Corretores
- [ ] Imóveis -	Cadastre seu imóvel
- [ ] Serviços - Extrato para proprietário
- [ ] Serviços - Financiamento e bancos
- [ ] Serviços - Boleto bancário
- [ ] Serviços - Cadastro de proposta
- [ ] Serviços - Cadastro de locatário
- [ ] Contato - Faça parte
- [ ] Contato - Fale conosco
- [ ] Contato - Universidade corporativa

**Comment by rdrgmoraes** [comment]
Feito!

**Comment by jesse1983** [comment]
@rdrgmoraes Discordo. 

1. Seria interessante ter pelo menos 1 link de cada categoria (serviços e institucional ficaram sem nada).
2. Nas chamadas da home há links para financiamento e encomende
![screen shot 2016-04-27 at 11 34 24](https://cloud.githubusercontent.com/assets/2489514/14855844/0c496418-0c6c-11e6-9f86-0f6ee41e33a6.png)

**Comment by rdrgmoraes** [comment]
@jesse1983, se quiser manter estas páginas no padrão você terá que incluir um feedback avisando que existe uma chamada vinculada aquela determinada página, questionando se o mesmo deseja realmente prosseguir removendo ambos, se o usuário escolher que sim, tanto a página quando a chamada terão de ser removidas.
