### ISSUE TITLE
Página contato.aspx com erro no mapa

### ISSUE THREAD

**Issue by stefanobaldo** [I-Value/CMS#9]
<img width="436" alt="screen shot 2016-03-10 at 14 35 47" src="https://cloud.githubusercontent.com/assets/1918151/13678446/7201a942-e6cd-11e5-9abd-afd695179b0b.png">

**Comment by ocipro** [comment]
![image](https://cloud.githubusercontent.com/assets/10051346/14257786/b54ba840-fa75-11e5-9447-9ae3d5366081.png)

Done.

Era só atualizar a procedure [virtualGaia].[sp_sel_realestate_offices]. Que foi alterada durante o desenvolvimento do CMS.


Esse erro acontece quando no cadastro de filiais, a filial foi cadastrada sem Latitude e Longitude.

Aproveitei e corrigi para a matriz ser sempre a primeira.
