### ISSUE TITLE
Link das chamadas

### ISSUE THREAD

**Issue by lucianonetto** [I-Value/CMS#90]
Link das chamadas, dois estão com erros

**Comment by jesse1983** [comment]
@lucianonetto Descreva melhor.

**Comment by lucianonetto** [comment]
http://luciano05.gaiasite.com.br/

nas chamadas o link de "Imóvel sob encomenda" e "Financiamento" dá erro, sendo que o site foi criado assim sem nenhuma alteração de link.

**Comment by rdrgmoraes** [comment]
Sugestão: O site deveria ser criado sem estas chamadas, o usuário as acrescenta se desejar, as chamadas possuem links para páginas que inicialmente não serão inclusas por padrão.

**Comment by jesse1983** [comment]
@stefanobaldo Por favor, dê um UPDATE no banco e troque todos os slugs: 
- `financimamento` por `financiamento-e-bancos` 
- `imovel-sob-encomenda` por `encomende-seu-imovel`

**Comment by stefanobaldo** [comment]
Corrigido
