### ISSUE TITLE
Página corretores

### ISSUE THREAD

**Issue by lucianonetto** [I-Value/CMS#91]
Quando não tem corretor cadastrado a página está em branco, o correto é ir para a página de não encontrou.

**Comment by rdrgmoraes** [comment]
Acredito que enviar o usuário para a página de não encontrou causará a percepção de bug. Sugiro que ao habilitar no CMS a página de corretores, seja exibida uma instrução relatando que a página somente será exibida no site caso existam corretores cadastrados e com as devidas informações preenchias. No site, a página somente deve ser exibida se estes critérios forem atendidos.

**Comment by jesse1983** [comment]
@rdrgmoraes pro usuário do site não fica claro o que realmente aconteceu com o link (que não é possível de tirar). Sugiro colocar uma mensagem de `Nenhum corretor foi configurado para aparecer no website`, além de deixar mais claro no CMS que ele deve cadastrar os usuários.

**Comment by rdrgmoraes** [comment]
@jesse1983, concordo.

**Comment by stefanobaldo** [comment]
<img width="621" alt="screen shot 2016-05-09 at 17 10 00" src="https://cloud.githubusercontent.com/assets/1918151/15126561/e731f1b2-1608-11e6-818b-3d7055e956eb.png">
