### ISSUE TITLE
Newsletter

### ISSUE THREAD

**Issue by lucianonetto** [I-Value/CMS#92]
Não é possível configurar o e-mail de recebimento de newsletter do rodapé, acho que seria interessante a possibilidade de desabilitar essa função também.

**Comment by jesse1983** [comment]
Concorda @rdrgmoraes ? É importante ter essa parte de newsletter no MVP?

**Comment by rdrgmoraes** [comment]
@jesse1983, concordo com o @lucianonetto, devemos manter e possibilitar ao usuário a configuração do e-mail de recepção.

**Comment by jesse1983** [comment]
Newsletter criada no CMS
@stefanobaldo  se chave `CONFIG.NEWSLETTER` estiver `true`, pode mostrar o campo. Enviar mensagem para `CONFIG.NEWSLETTER.TO`

**Comment by stefanobaldo** [comment]
Resolvido!
