### ISSUE TITLE
Não está mostrando uma filial cadastrada

### ISSUE THREAD

**Issue by jesse1983** [I-Value/CMS#98]
Testar no site http://jorge_lopes_lima.gaiasite.com.br

# NO CMS
![screen shot 2016-04-26 at 17 34 13](https://cloud.githubusercontent.com/assets/2489514/14835259/3f475736-0bdf-11e6-8af3-b00461924f38.png) 

============
# NO SITE
![screen shot 2016-04-26 at 18 47 05](https://cloud.githubusercontent.com/assets/2489514/14835275/54abbe46-0bdf-11e6-8860-833e84856c0a.png)

**Comment by lucianonetto** [comment]
Quando oculto uma unidade no cms, mesmo assim continua aparecendo no site, tanto no rodapé quanto na página de contato.

**Comment by stefanobaldo** [comment]
Corrigidos os dois problemas

**Comment by lucianonetto** [comment]
Precisa sumir também o endereço e mapa na página de contato, quando oculta a unidade no cms.

**Comment by stefanobaldo** [comment]
Corrigido
