### ISSUE TITLE
Ajustar cor da fonte em conformidade com a configuração do CMS

### ISSUE THREAD

**Issue by rdrgmoraes** [I-Value/CMS#99]
![image](https://cloud.githubusercontent.com/assets/17769443/14835366/c4bad9ba-0bdf-11e6-81b5-75468fa793c6.png)

![image](https://cloud.githubusercontent.com/assets/17769443/14835515/8c41d880-0be0-11e6-95d4-61a1cf43e696.png)

**Comment by lucianonetto** [comment]
Feito, irei commitar no fim do dia.
